kind: pipeline
type: docker
name: Caddy Docker Container

steps:
- name: restore-cache-with-filesystem
  image: meltwater/drone-cache:v1.1.0-rc1
  pull: always
  settings:
    archive_format: gzip
    backend: filesystem
    cache_key: volume
    restore: true
    exit_code: true
  volumes:
    - name: cache
      path: /tmp/cache

- name: docker-build-publish  
  image: plugins/docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: rajaseg/caddy
    dockerfile: Dockerfile
    auto_tag: true
    
- name: rebuild-cache-with-filesystem
  image: meltwater/drone-cache:v1.1.0-rc1
  pull: always
  settings:
    archive_format: gzip
    backend: filesystem
    cache_key: volume
    rebuild: true
    exit_code: true
  volumes:
    - name: cache
      path: /tmp/cache
      
- name: scan
  image: aquasecurity/trivy-action@0.31.0
  #quay.io/sighup/trivy-offline:latest
  pull: always
  commands:
    - trivy image --skip-db-update python:3.4-alpine
      
volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
- name: cache
  temp: {}
when:
  event: push
  branch: [master]
  status: [changed, failure]
